version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file: 
      - ./common.env
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on: 
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    expose:
      - "80"
    env_file:
      - ./common.env
    depends_on: 
      - web
    links:
      - web
